language: node_js
node_js:
  - iojs
  - 8
cache:
  directories:
    - node_modules
  yarn: true
script:
  - yarn build
  - yarn test --coverage && type||cat ./coverage/lcov.info | coveralls
install: true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master